name: build-and-push-to-dockerhub

on:
  release:
    types:
      - created
  # push:
  #   branches:
  #     - master
  # pull_request:
  #   branches:
  #     - master
  # workflow_dispatch:

env:
    DOCKER_IMAGE: kamalyes/whistle
    TAG_NAME: ${{github.ref_name}}
      
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Tag Name
        run: |
          echo "Tag name from github.ref_name: ${{env.TAG_NAME}}"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        id: prepare
        run: |
          DOCKER_IMAGE=${{env.DOCKER_IMAGE}}
          DOCKER_PLATFORMS=linux/amd64,linux/arm64
          TAG_NAME=${{env.TAG_NAME}}
          DOCKER_IMAGE_TAGS="--tag ${DOCKER_IMAGE}:${TAG_NAME}"
          echo ::set-output name=docker_image::${DOCKER_IMAGE}
          echo ::set-output name=version::${TAG_NAME}
          echo ::set-output name=buildx_args::--platform ${DOCKER_PLATFORMS} \
            --build-arg VERSION=${TAG_NAME} \
            --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
            --build-arg VCS_REF=${GITHUB_SHA::8} \
            ${DOCKER_IMAGE_TAGS} .
      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3
      - name: Docker Buildx (build)
        run: |
          docker buildx build --file Dockerfile --output "type=image,push=false" ${{ steps.prepare.outputs.buildx_args }}
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Docker Buildx (push)
        run: |
          docker buildx build --file Dockerfile --output "type=image,push=true" ${{ steps.prepare.outputs.buildx_args }}